version: '3.8'
services:
  client:
    build: ./client/
    container_name: client
    ports:
      - "5173:5173"
    command: npm run client
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
  server:
    build: ./server/
    container_name: server
    ports:
      - "3700:3700"
    command: npm run server
    environment:
      MONGO_URI: mongodb://root:root@db:27017
    volumes:
      - "./server/:/app"
      - "/app/node_modules"   
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db-data:/data/db
volumes:
  db-data: {}

  
