apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: jassercherif/server:v1.0
          ports:
            - containerPort: 3700
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - port: 3700
      targetPort: 3700
  selector:
    app: server
  type: NodePort
